### ISSUE TITLE
Script to capture and anonymize pcap

### ISSUE THREAD

**Issue by tarunmangla** [vermish6/Minor-Project-#1]
- Script that captures network traffic in a rotating manner. 
- Once a new pcap is generated the script anonymizes the IP address of the pcap using cryptopan. Only anonymize IITD IP addresses. 10.0.0.0/8 and the IPs listed in https://ipinfo.io/AS132780#block-ranges
- Start a capture and run it for a day and collect the anonymized trace

**Comment by vermish6** [comment]
This issue has been resolved ooly IITD subnet ones are anonymized and data is captured in an anonymized manner
